#!/bin/bash

output=frontend.rs

cat << EOF > $output
// This file was generated by the generate.sh script.
// DO NOT EDIT THIS FILE MANUALLY!

use lelwel::frontend::diag::*;

macro_rules! check_next {
    (\$diags: ident, \$message: expr) => {
        assert_eq!(\$diags.next().unwrap().to_string(), \$message);
    };
}
macro_rules! check_empty {
    (\$diags: ident) => {
        if !\$diags.next().is_none() {
            panic!("too many {}", stringify!(\$diags))
        }
    };
}

fn gen_diag(input: &str) -> std::io::Result<Diag> {
    let (_, diag) = lelwel::llw_to_ast(input)?;
    Ok(diag)
}
EOF

for path in frontend/*.llw; do
  file=${path##*/}
  cat << EOF >> $output

#[test]
#[rustfmt::skip]
fn ${file%.llw}() {
    let diag = gen_diag("tests/$path").unwrap();
    let mut errors = diag.error_iter();
    let mut warnings = diag.warning_iter();
EOF
  diag=$(llw -c "$path" 2>&1 > /dev/null)
  echo >> $output
  echo "$diag" | grep 'error: ' | while read -r line ; do
    echo "$line" | sed 's/^[^:]*: \(.*\)/    check_next!(errors, "tests\/\1");/' >> $output
  done
  echo '    check_empty!(errors);' >> $output
  echo >> $output
  echo "$diag" | grep 'warning: ' | while read -r line ; do
    echo "$line" | sed 's/^[^:]*: \(.*\)/    check_next!(warnings, "tests\/\1");/' >> $output
  done
  echo '    check_empty!(warnings);' >> $output
  echo '}' >> $output
done

