[package]
name = "lelwel-l"
version = "0.0.0"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
logos = "0.14.0"
codespan-reporting = "0.11.1"
wasm-bindgen = "0.2.92"

[build-dependencies]
lelwel = { path = "../.." }
