[package]
name = "lelwel-json"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
codespan-reporting = "0.11.1"

[build-dependencies]
lelwel = { path = "../.." }
